// <auto-generated />
using System;
using AirTrack.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirTrack.Server.Migrations
{
    [DbContext(typeof(AirTrackContext))]
    [Migration("20260710034757_UpdateMxFields")]
    partial class UpdateMxFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("AirTrack.Server.Models.Aircraft.AircraftBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AnnualDueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EngineType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Equipment")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Hobbs")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Seats")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SquawkCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Tach")
                        .HasColumnType("TEXT");

                    b.Property<string>("TailNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TailNumber")
                        .IsUnique();

                    b.ToTable("Aircraft", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("AirTrack.Server.Models.Aircraft.RecurringAD", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ADNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AircraftId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CessnaSkyhawkId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IntervalHours")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastCompliedWith")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PiperArrowId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PiperSeminoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RobinsonR44Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.HasIndex("CessnaSkyhawkId");

                    b.HasIndex("PiperArrowId");

                    b.HasIndex("PiperSeminoleId");

                    b.HasIndex("RobinsonR44Id");

                    b.ToTable("RecurringADs");
                });

            modelBuilder.Entity("AirTrack.Server.Models.Maintenance.Squawk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AircraftId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGrounding")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MechanicSignoff")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolutionNotes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.ToTable("Squawks");
                });

            modelBuilder.Entity("AirTrack.Server.Models.People.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Certifications")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("AirTrack.Server.Models.People.Mechanic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CertificationNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Mechanics");
                });

            modelBuilder.Entity("AirTrack.Server.Models.People.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedInstructorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssignedInstructorId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("AirTrack.Server.Models.Scheduler.FlightEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AircraftId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("End")
                        .HasColumnType("TEXT");

                    b.Property<int?>("InstructorId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MechanicId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Start")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FlightEvents");
                });

            modelBuilder.Entity("AirTrack.Server.Models.Aircraft.CessnaSkyhawk", b =>
                {
                    b.HasBaseType("AirTrack.Server.Models.Aircraft.AircraftBase");

                    b.Property<DateTime?>("ELTInspectionDue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Last100Hr")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Last50Hr")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LastOilChange")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PitotStaticDue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TransponderDue")
                        .HasColumnType("TEXT");

                    b.ToTable("CessnaSkyhawks", (string)null);
                });

            modelBuilder.Entity("AirTrack.Server.Models.Aircraft.PiperArrow", b =>
                {
                    b.HasBaseType("AirTrack.Server.Models.Aircraft.AircraftBase");

                    b.Property<decimal>("Last100Hr")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastGearCyclesInspection")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LastOilChange")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PropOverhaulDue")
                        .HasColumnType("TEXT");

                    b.ToTable("PiperArrows", (string)null);
                });

            modelBuilder.Entity("AirTrack.Server.Models.Aircraft.PiperSeminole", b =>
                {
                    b.HasBaseType("AirTrack.Server.Models.Aircraft.AircraftBase");

                    b.Property<decimal>("Last100Hr")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastGearCyclesInspection")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LastLeftEngineHobbs")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LastRightEngineHobbs")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LeftPropOverhaulDue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RightPropOverhaulDue")
                        .HasColumnType("TEXT");

                    b.ToTable("PiperSeminoles", (string)null);
                });

            modelBuilder.Entity("RobinsonR44", b =>
                {
                    b.HasBaseType("AirTrack.Server.Models.Aircraft.AircraftBase");

                    b.Property<decimal>("BladeLifeRemaining")
                        .HasColumnType("TEXT");

                    b.Property<int>("ClutchActuationCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("GovernorInspectionDue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Last2200HrOverhaul")
                        .HasColumnType("TEXT");

                    b.ToTable("RobinsonR44s", (string)null);
                });

            modelBuilder.Entity("AirTrack.Server.Models.Aircraft.RecurringAD", b =>
                {
                    b.HasOne("AirTrack.Server.Models.Aircraft.AircraftBase", "Aircraft")
                        .WithMany()
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirTrack.Server.Models.Aircraft.CessnaSkyhawk", null)
                        .WithMany("RecurringADs")
                        .HasForeignKey("CessnaSkyhawkId");

                    b.HasOne("AirTrack.Server.Models.Aircraft.PiperArrow", null)
                        .WithMany("RecurringADs")
                        .HasForeignKey("PiperArrowId");

                    b.HasOne("AirTrack.Server.Models.Aircraft.PiperSeminole", null)
                        .WithMany("RecurringADs")
                        .HasForeignKey("PiperSeminoleId");

                    b.HasOne("RobinsonR44", null)
                        .WithMany("RecurringADs")
                        .HasForeignKey("RobinsonR44Id");

                    b.Navigation("Aircraft");
                });

            modelBuilder.Entity("AirTrack.Server.Models.Maintenance.Squawk", b =>
                {
                    b.HasOne("AirTrack.Server.Models.Aircraft.AircraftBase", "Aircraft")
                        .WithMany()
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aircraft");
                });

            modelBuilder.Entity("AirTrack.Server.Models.People.Student", b =>
                {
                    b.HasOne("AirTrack.Server.Models.People.Instructor", "AssignedInstructor")
                        .WithMany("Students")
                        .HasForeignKey("AssignedInstructorId");

                    b.Navigation("AssignedInstructor");
                });

            modelBuilder.Entity("AirTrack.Server.Models.Aircraft.CessnaSkyhawk", b =>
                {
                    b.HasOne("AirTrack.Server.Models.Aircraft.AircraftBase", null)
                        .WithOne()
                        .HasForeignKey("AirTrack.Server.Models.Aircraft.CessnaSkyhawk", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AirTrack.Server.Models.Aircraft.PiperArrow", b =>
                {
                    b.HasOne("AirTrack.Server.Models.Aircraft.AircraftBase", null)
                        .WithOne()
                        .HasForeignKey("AirTrack.Server.Models.Aircraft.PiperArrow", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AirTrack.Server.Models.Aircraft.PiperSeminole", b =>
                {
                    b.HasOne("AirTrack.Server.Models.Aircraft.AircraftBase", null)
                        .WithOne()
                        .HasForeignKey("AirTrack.Server.Models.Aircraft.PiperSeminole", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RobinsonR44", b =>
                {
                    b.HasOne("AirTrack.Server.Models.Aircraft.AircraftBase", null)
                        .WithOne()
                        .HasForeignKey("RobinsonR44", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AirTrack.Server.Models.People.Instructor", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("AirTrack.Server.Models.Aircraft.CessnaSkyhawk", b =>
                {
                    b.Navigation("RecurringADs");
                });

            modelBuilder.Entity("AirTrack.Server.Models.Aircraft.PiperArrow", b =>
                {
                    b.Navigation("RecurringADs");
                });

            modelBuilder.Entity("AirTrack.Server.Models.Aircraft.PiperSeminole", b =>
                {
                    b.Navigation("RecurringADs");
                });

            modelBuilder.Entity("RobinsonR44", b =>
                {
                    b.Navigation("RecurringADs");
                });
#pragma warning restore 612, 618
        }
    }
}
