// <auto-generated />
using System;
using AirTrack.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirTrack.Server.Migrations
{
    [DbContext(typeof(AirTrackContext))]
    partial class AirTrackContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("AirTrack.Model.Aircraft.AircraftBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AnnualDueDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CurrentFlightStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentInstructor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStudent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Hobbs")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextBookingEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextBookingStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("SquawkCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Tach")
                        .HasColumnType("TEXT");

                    b.Property<string>("TailNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TailNumber")
                        .IsUnique();

                    b.ToTable("Aircraft", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("AirTrack.Model.Aircraft.RecurringAD", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ADNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AircraftId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CessnaSkyhawkId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IntervalHours")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastCompliedWith")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PiperArrowId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PiperSeminoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RobinsonR44Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.HasIndex("CessnaSkyhawkId");

                    b.HasIndex("PiperArrowId");

                    b.HasIndex("PiperSeminoleId");

                    b.HasIndex("RobinsonR44Id");

                    b.ToTable("RecurringADs");
                });

            modelBuilder.Entity("AirTrack.Models.Maintenance.CorrectiveAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LaborHours")
                        .HasColumnType("TEXT");

                    b.Property<int>("MechanicId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PartsUsed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RecurringADId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MechanicId");

                    b.HasIndex("RecurringADId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("CorrectiveActions");
                });

            modelBuilder.Entity("AirTrack.Models.Maintenance.MechanicSignoff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CertificateNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MechanicId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SignedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SignoffText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MechanicId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("MechanicSignoffs");
                });

            modelBuilder.Entity("AirTrack.Models.Maintenance.Squawk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AircraftId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGrounding")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.ToTable("Squawks");
                });

            modelBuilder.Entity("AirTrack.Models.Maintenance.WorkOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedMechanicId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SquawkId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssignedMechanicId");

                    b.HasIndex("SquawkId")
                        .IsUnique();

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("AirTrack.Models.People.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Certifications")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("AirTrack.Models.People.Mechanic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CertificationNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Mechanics");
                });

            modelBuilder.Entity("AirTrack.Models.People.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedInstructorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssignedInstructorId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("AirTrack.Model.Aircraft.CessnaSkyhawk", b =>
                {
                    b.HasBaseType("AirTrack.Model.Aircraft.AircraftBase");

                    b.Property<DateTime?>("ELTInspectionDue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HoursSinceLast100Hr")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HoursSinceLast50Hr")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HoursSinceLastOilChange")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PitotStaticDue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TransponderDue")
                        .HasColumnType("TEXT");

                    b.ToTable("CessnaSkyhawks", (string)null);
                });

            modelBuilder.Entity("AirTrack.Model.Aircraft.PiperArrow", b =>
                {
                    b.HasBaseType("AirTrack.Model.Aircraft.AircraftBase");

                    b.Property<int>("GearCyclesSinceInspection")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("HoursSinceLast100Hr")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HoursSinceLastOilChange")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PropOverhaulDue")
                        .HasColumnType("TEXT");

                    b.ToTable("PiperArrows", (string)null);
                });

            modelBuilder.Entity("AirTrack.Model.Aircraft.PiperSeminole", b =>
                {
                    b.HasBaseType("AirTrack.Model.Aircraft.AircraftBase");

                    b.Property<int>("GearCyclesSinceInspection")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LeftEngineHours")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LeftPropOverhaulDue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RightEngineHours")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RightPropOverhaulDue")
                        .HasColumnType("TEXT");

                    b.ToTable("PiperSeminoles", (string)null);
                });

            modelBuilder.Entity("RobinsonR44", b =>
                {
                    b.HasBaseType("AirTrack.Model.Aircraft.AircraftBase");

                    b.Property<decimal>("BladeLifeRemaining")
                        .HasColumnType("TEXT");

                    b.Property<int>("ClutchActuationCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("GovernorInspectionDue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HoursSince2200HrOverhaul")
                        .HasColumnType("TEXT");

                    b.ToTable("RobinsonR44s", (string)null);
                });

            modelBuilder.Entity("AirTrack.Model.Aircraft.RecurringAD", b =>
                {
                    b.HasOne("AirTrack.Model.Aircraft.AircraftBase", "Aircraft")
                        .WithMany()
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirTrack.Model.Aircraft.CessnaSkyhawk", null)
                        .WithMany("RecurringADs")
                        .HasForeignKey("CessnaSkyhawkId");

                    b.HasOne("AirTrack.Model.Aircraft.PiperArrow", null)
                        .WithMany("RecurringADs")
                        .HasForeignKey("PiperArrowId");

                    b.HasOne("AirTrack.Model.Aircraft.PiperSeminole", null)
                        .WithMany("RecurringADs")
                        .HasForeignKey("PiperSeminoleId");

                    b.HasOne("RobinsonR44", null)
                        .WithMany("RecurringADs")
                        .HasForeignKey("RobinsonR44Id");

                    b.Navigation("Aircraft");
                });

            modelBuilder.Entity("AirTrack.Models.Maintenance.CorrectiveAction", b =>
                {
                    b.HasOne("AirTrack.Models.People.Mechanic", "Mechanic")
                        .WithMany()
                        .HasForeignKey("MechanicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirTrack.Model.Aircraft.RecurringAD", "RecurringAD")
                        .WithMany()
                        .HasForeignKey("RecurringADId");

                    b.HasOne("AirTrack.Models.Maintenance.WorkOrder", "WorkOrder")
                        .WithMany("Actions")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mechanic");

                    b.Navigation("RecurringAD");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("AirTrack.Models.Maintenance.MechanicSignoff", b =>
                {
                    b.HasOne("AirTrack.Models.People.Mechanic", "Mechanic")
                        .WithMany()
                        .HasForeignKey("MechanicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirTrack.Models.Maintenance.WorkOrder", "WorkOrder")
                        .WithMany()
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mechanic");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("AirTrack.Models.Maintenance.Squawk", b =>
                {
                    b.HasOne("AirTrack.Model.Aircraft.AircraftBase", "Aircraft")
                        .WithMany()
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aircraft");
                });

            modelBuilder.Entity("AirTrack.Models.Maintenance.WorkOrder", b =>
                {
                    b.HasOne("AirTrack.Models.People.Mechanic", "AssignedMechanic")
                        .WithMany()
                        .HasForeignKey("AssignedMechanicId");

                    b.HasOne("AirTrack.Models.Maintenance.Squawk", "Squawk")
                        .WithOne("WorkOrder")
                        .HasForeignKey("AirTrack.Models.Maintenance.WorkOrder", "SquawkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedMechanic");

                    b.Navigation("Squawk");
                });

            modelBuilder.Entity("AirTrack.Models.People.Student", b =>
                {
                    b.HasOne("AirTrack.Models.People.Instructor", "AssignedInstructor")
                        .WithMany("Students")
                        .HasForeignKey("AssignedInstructorId");

                    b.Navigation("AssignedInstructor");
                });

            modelBuilder.Entity("AirTrack.Model.Aircraft.CessnaSkyhawk", b =>
                {
                    b.HasOne("AirTrack.Model.Aircraft.AircraftBase", null)
                        .WithOne()
                        .HasForeignKey("AirTrack.Model.Aircraft.CessnaSkyhawk", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AirTrack.Model.Aircraft.PiperArrow", b =>
                {
                    b.HasOne("AirTrack.Model.Aircraft.AircraftBase", null)
                        .WithOne()
                        .HasForeignKey("AirTrack.Model.Aircraft.PiperArrow", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AirTrack.Model.Aircraft.PiperSeminole", b =>
                {
                    b.HasOne("AirTrack.Model.Aircraft.AircraftBase", null)
                        .WithOne()
                        .HasForeignKey("AirTrack.Model.Aircraft.PiperSeminole", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RobinsonR44", b =>
                {
                    b.HasOne("AirTrack.Model.Aircraft.AircraftBase", null)
                        .WithOne()
                        .HasForeignKey("RobinsonR44", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AirTrack.Models.Maintenance.Squawk", b =>
                {
                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("AirTrack.Models.Maintenance.WorkOrder", b =>
                {
                    b.Navigation("Actions");
                });

            modelBuilder.Entity("AirTrack.Models.People.Instructor", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("AirTrack.Model.Aircraft.CessnaSkyhawk", b =>
                {
                    b.Navigation("RecurringADs");
                });

            modelBuilder.Entity("AirTrack.Model.Aircraft.PiperArrow", b =>
                {
                    b.Navigation("RecurringADs");
                });

            modelBuilder.Entity("AirTrack.Model.Aircraft.PiperSeminole", b =>
                {
                    b.Navigation("RecurringADs");
                });

            modelBuilder.Entity("RobinsonR44", b =>
                {
                    b.Navigation("RecurringADs");
                });
#pragma warning restore 612, 618
        }
    }
}
